/**
 * Re-verify every committed field map against the form geometry, and re-apply
 * human adjudications on top.
 *
 * Run:  npx vite-node tools/revalidate-maps.ts [--write]
 *
 * Verification is not a one-off gate at discovery time. It tightens: the empty
 * label check was added after the maps were generated, and it immediately found
 * an entry that had passed the looser version — locating the empty string in
 * any text trivially succeeds, so a mapping citing nothing had been sitting in
 * a committed file looking exactly like one citing a real printed label.
 *
 * Running the current checks over stored maps is deterministic and free, and it
 * is also where adjudications get re-applied — so a map regenerated by a fresh
 * discovery run cannot quietly lose a correction a human already made.
 */
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  adjudicate,
  admitMappings,
  type Adjudication,
  type FieldMap,
  type FormGeometry,
} from "../src/lib/formmap";

const ADJUDICATIONS: Adjudication[] = (
  JSON.parse(readFileSync("src/forms/adjudications.json", "utf8")) as {
    adjudications: Adjudication[];
  }
).adjudications;

const GEO = "src/forms/geometry";
const MAPS = process.env.WK_MAPS ?? "src/forms/maps";
const write = process.argv.includes("--write");

let demoted = 0;
let corrected = 0;

for (const file of readdirSync(MAPS).filter((f) => f.endsWith(".json"))) {
  const map = JSON.parse(readFileSync(join(MAPS, file), "utf8")) as FieldMap;
  const geometry = JSON.parse(
    readFileSync(join(GEO, `${map.form}.json`), "utf8"),
  ) as FormGeometry;

  const raw = admitMappings(
    geometry,
    map.entries.map((e) => ({
      field: e.field,
      target: e.target,
      labelQuote: e.labelQuote,
      onState: e.onState,
      condition: e.condition,
    })),
  );

  const { run, applied, refused } = adjudicate(raw, geometry, ADJUDICATIONS);
  const bad = run.proposals.filter(
    (p) => p.verdict !== "verified" && p.verdict !== "unmapped",
  );

  console.log(
    `${map.form.padEnd(10)} ${map.entries.length} entries -> ` +
      `${run.verified.length} verified, ${bad.length} failing, ${applied.length} adjudicated`,
  );
  for (const a of applied) {
    console.log(`    corrected  ${a.field.split(".").pop()}  ->  ${a.target}  (${a.decidedBy})`);
  }
  for (const b of bad) {
    console.log(`    ${b.verdict.padEnd(22)} ${b.field.split(".").pop()}  ->  ${b.target}`);
  }
  for (const r of refused) {
    console.log(`    ADJUDICATION REFUSED  ${r.field.split(".").pop()}: ${r.note.slice(0, 90)}`);
  }
  demoted += bad.length;
  corrected += applied.length;

  if (write) {
    // Rewritten from the verified set rather than by filtering the old entries,
    // so an adjudication that changed a target is actually persisted.
    map.entries = run.verified.map((m) => ({
      field: m.field,
      target: m.target,
      labelQuote: m.labelQuote,
      page: m.page ?? 0,
      type: m.type ?? "",
      ...(m.onState ? { onState: m.onState } : {}),
      ...(m.condition ? { condition: m.condition } : {}),
    }));
    map.rejected = [
      ...map.rejected.filter((r) => !bad.some((b) => b.field === r.field)),
      ...bad.map((b) => ({ field: b.field, verdict: b.verdict, note: b.note })),
    ];
    writeFileSync(join(MAPS, file), JSON.stringify(map, null, 1));
  }
}

console.log(
  `\n${corrected} adjudication${corrected === 1 ? "" : "s"} applied, ` +
    (demoted === 0
      ? "no mapping fails the current checks."
      : `${demoted} failing${write ? " — demoted to rejected." : ". re-run with --write."}`),
);
